version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: pyriboo
      MONGO_INITDB_ROOT_PASSWORD: 8AQdfFXiANVogQzw
      MONGO_INITDB_DATABASE: guitarchi
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
